/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSite: typeof import('./src/components/DataModel/AboutSite.vue')['default']
    AddPlaylist: typeof import('./src/components/DataModel/AddPlaylist.vue')['default']
    AddToPlaylistModal: typeof import('./src/components/DataModel/AddToPlaylistModal.vue')['default']
    AdminDashboard: typeof import('./src/components/Admin/AdminDashboard.vue')['default']
    AllArtists: typeof import('./src/components/DataList/AllArtists.vue')['default']
    BigPlayer: typeof import('./src/components/Player/BigPlayer.vue')['default']
    CreatePlaylistModal: typeof import('./src/components/DataModel/CreatePlaylistModal.vue')['default']
    Nav: typeof import('./src/components/Nav/index.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NUpload: typeof import('naive-ui')['NUpload']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    Player: typeof import('./src/components/Player/index.vue')['default']
    PlayerControl: typeof import('./src/components/Player/PlayerControl.vue')['default']
    PlayerCover: typeof import('./src/components/Player/PlayerCover.vue')['default']
    PlayerRecord: typeof import('./src/components/Player/PlayerRecord.vue')['default']
    PlayList: typeof import('./src/components/DataList/PlayList.vue')['default']
    PlaylistGrid: typeof import('./src/components/DataList/PlaylistGrid.vue')['default']
    PlaylistUpdate: typeof import('./src/components/DataModel/PlaylistUpdate.vue')['default']
    Provider: typeof import('./src/components/Provider/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongList: typeof import('./src/components/DataList/SongList.vue')['default']
    SystemStats: typeof import('./src/components/Home/SystemStats.vue')['default']
  }
}
