Server:
  Mode: debug # debug | release
  Port: :12345
  DbType: "sqlite" # mongoDb | sqlite
  DbAutoMigrate: true # 是否自动迁移数据库表结构 (表结构没变可以不迁移, 提高启动速度)
  DbLogMode: "error" # 日志级别 silent, error, warn, info, 默认 info

Log:
  Level: "debug" # debug | info | warn | error
  Format: "text" # text | json
  Directory: "log"
  
JWT:
  Secret: "123456"
  Expire: 24 # hour
  Issuer: "123456"
  
Sqlite:
  Dsn: "data.db"
  
Session:
  Name: "randolfluo"
  Salt: "salt123"
  MaxAge: 600 # second

BasicPath:
  FilePath: 'C:\Users\lrj32\Desktop\music player'
  FileName: 'localmusicplayerFoleder'

Redis:
  Addr: "127.0.0.1:6379"
  Password: ""
  DB: 0

QwenTTS:
  ApiKey: "" # 阿里云百炼 API Key，若为空则从环境变量中获取
  Model: "qwen3-tts-flash"  # 模型名称
  Voice: "Neil"  # 语音名称
  Format: "flac"  # 音频格式
  SampleRate: 24000  # 采样率
  Volume: 50  # 音量
  Rate: 1.0  # 语速
  Pitch: 1.0  # 语调

SiliconFlow:
  ApiKey: "" # 硅基流动 API Key，若为空则从环境变量中获取
  Model: "Qwen/Qwen3-8B"  # 模型名称

